---
- hosts: 127.0.0.1
  vars_files:
    - vars/druid.yml
  tasks:
    - name: Preflight check AWS_KEYS
      assert:
        that: druid_s3_accessKey != '<AWS_ACCESS_KEY>' and druid_s3_secretKey != '<AWS_SECRET_KEY>'

- hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - vars/druid.yml
  roles:
    - java

- hosts: tag_metrics_master
  vars_files:
    - vars/metrics.yml
  become: yes
  roles:
    - influxdb
    - grafana

  post_tasks:
    - name: Install influxdb python module
      pip:
        name: influxdb

    - name: Create influxdb database for druid metrics
      influxdb_database:
        hostname: "{{ ansible_fqdn | default(ansible_host) | default(inventory_hostname) }}"
        database_name: druid

    - name: Enable graphite in package-provided config
      blockinfile:
        dest: "{{ influxdb_config_file }}"
        marker: "  # {mark} ANSIBLE MANAGED GRAPHITE ENABLEMENT BLOCK"
        insertafter: ^\[\[graphite\]\]
        block: |2
            enabled = true
            database = "druid"
            templates = [
              "*.*.*.*.*.* env.service.hostname.dim1.dim2.measurement*",
              "*.*.*.*.* env.service.hostname.dim1.measurement*",
              "*.*.*.* env.service.hostname.measurement*"
            ]
      notify:
        - restart influxdb

    - name: Add kapacitor for influx db alerting
      yum:
        name: kapacitor

    - name: Add chronograf for influxdb exploration
      yum:
        name: chronograf

    - name: Start kapacitor and chronograf
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - kapacitor
        - chronograf

    - name: Enable systemd for services
      service:
        name: "{{ item }}"
        enabled: yes
      with_items:
        - kapacitor
        - chronograf

- hosts: tag_postgres_master
  vars_files:
    - vars/druid.yml
  become: yes
  roles:
    - postgres-common
    - { role: postgres-druid, become_user: postgres }

- hosts: tag_zookeeper_master:tag_zookeeper_slave
  vars_files:
    - vars/druid.yml
  become: yes
  roles:
    - zookeeper

- hosts: tag_Name_druid_cluster_node:!tag_postgres_master:!tag_metrics_master
  vars_files:
    - vars/druid.yml
  become: yes
  roles:
    - supervisor
    - druid-common

- hosts: tag_druid_historical
  vars_files:
    - vars/druid.yml
  become: yes
  roles:
    - historical
      
- hosts: tag_druid_coordinator
  vars_files:
    - vars/druid.yml
  become: yes
  roles:
    - coordinator
   
- hosts: tag_druid_broker
  vars_files:
    - vars/druid.yml
  become: yes
  roles:
    - broker

- hosts: tag_druid_middlemanager
  vars_files:
    - vars/druid.yml
  become: yes
  roles:
    - historical
    - middle-manager

